### ISSUE TITLE
Macのアプリが立ち上がりません。

### ISSUE THREAD

**Issue by aki-wada** [sony/nnc-desktop#5]
Apple M2 環境にて、mac app をダウンロードし、実行しましたが立ち上がりません。
また、実行までにいくつかの手順が必要でした。
ログを見たところ、立ち上がらない理由として以下が考えられました（生成AIのサジェスチョンです）。

 
![SNNC_mac](https://github.com/user-attachments/assets/282f121f-cff4-499d-991f-83a632461861)

**Comment by aki-wada** [comment]
It appears you're encountering a Python library loading error when trying to run NeuralNetworkConsoleDesktop. The error indicates that the application is looking for Python 3.10 in a specific location but can't find it. Let me break down the issue:
The error is trying to find: /Users/ec2-user/.anyenv/envs/pyenv/versions/3.10.14/lib/libpython3.10.dylib
This error occurs because:
The application is expecting Python 3.10.14 to be installed via pyenv in an ec2-user directory
The library path doesn't match your current system configuration (you're logged in as *************, not ec2-user)

NeuralNetworkConsoleDesktopの起動時にPythonライブラリの読み込みエラーが発生しているようです。具体的な問題を説明させていただきます：
エラーの内容：
アプリケーションがPython 3.10のライブラリ（libpython3.10.dylib）を特定の場所で探していますが、見つけることができません
具体的には/Users/ec2-user/.anyenv/envs/pyenv/versions/3.10.14/lib/というパスを探しています
現在は********というユーザーで実行していますが、アプリケーションはec2-userというパスを参照しようとしています

**Comment by TomonobuTsujikawa** [comment]
@aki-wada san,
Thank you for providing detail information!

We found that this issue is dependent on the build environment, and we'll prepare bugfix release.
We recommend waiting until the bugfix version is released.
But if you would like to try it with current version, please try:

Open terminal, then set the environment variables and remove library. (`NNCD_PATH` is the installation path)
```bash
export NNCD_PATH=/Applications/NeuralNetworkConsoleDesktop.app/Contents/Resources/python_bundles
export DYLD_LIBRARY_PATH=$NNCD_PATH/lib:$NNCD_PATH/lib/python3.10/lib-dynload:$NNCD_PATH/bin
rm -f $NNCD_PATH/lib/python3.10/lib-dynload/libssl.3.dylib
```
Then, start nncd from terminal.

**Comment by TomonobuTsujikawa** [comment]
v0.2.1 was released. Please check https://techhub.developer.sony.com/ja/neural-network-console

**Comment by aki-wada** [comment]
稼動しました。CPUx1 で動きましたが、データセットを大きくするとメモリが足りずハングアップします。
Due to the memory size required by the parameter is too large, the job cannot be executed on the selected CPU / GPU. Please review the network and reduce the data set size so that it can be processed with the memory of the selected CPU / GPU, or try a superordinate GPU.

今後の改善をお待ちしています。よろしくお願いします。
